config/routes.rb
Rails.application.routes.draw do

  devise_for :podcasts
  root 'welcome#index'

  resources :podcasts, only: [:index, :show]

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit :email, :password, :password_confirmation, :title}
  		devise_parameter_sanitizer.for(:account_update) { |u| u.permit :email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay}
   end

end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController

	def index
		@podcast = Podcast.all.order("created_at DESC")
	end

	def show
		@podcast = Podcast.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PODCAST.FM</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Explore", podcasts_path%></li>
        <% if podcast_signed_in? %>
            <li><%= link_to 'Sign Out', destroy_podcast_session_path, method: :delete%></li>
            <li><a href="">Dashboard</a></li>
        <% else %>
            <li><%= link_to "Sign In", new_podcast_session_path %></li>
        <% end %>
        <li><a href="#">Create a Podcast</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodcastFm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700italic,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render 'layouts/navbar' %>


<%= yield %>

</body>
</html>

app/views/podcasts/index.html.erb
<div class="banner-podcasts">
  <img src="<%= asset_path 'banner3'%>">
  <h2 id="banner-sign-in-h1">Discover your new favourite podcast</h2>
</div>

<div class="container">

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
      </div>
    </div>
  </div>
</div>

</div>

<% @podcast.each do |podcast| %>
	 <div class="thumbnail">
      	<div class="caption">
        	<img src="..." alt="...">
        	<h3><%= podcast.title %></h3>
       		<p><%= podcast.description %></p>
        </div>
    </div>
<% end %>

app/views/podcasts/show.html.erb
<div class="container podcast_show">
	<h1><%= @podcast.title + " Podcast"%></h1>
	<p><%= @podcast.description %></p>

	<a href="<%= @podcast.itunes %>">iTunes</a>
	<a href="<%= @podcast.podbay %>">Podbay</a>
	<a href="<%= @podcast.stitcher %>">Stitcher</a>

</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h1 id="header">Discour your new favourite <br>podcast, or create your own</h1>
	<%= link_to "Create a Podcast", new_podcast_registration_path, class: "button button_highlight"%>
	<%= link_to "Explore", podcasts_path, class: "button button_white"%>
</div>